### PR TITLE
Removed superfluous "logging enhancer initiated" message

### PR DESCRIPTION
**Pull request by drewzh**

### CODE REVIEW

**Comment by bbottema** [comment]
@drewzh, do you have a specific reason why you don't like the message? I can't tailor to everybody's specific tastes, so I would like to hear some argument that would benefit the community at large.

**Comment by drewzh** [comment]
I just don't understand why the log message is there to begin with? It just seems a bit spammy?

Maybe I'm being a bit picky but all my logs are in the global namespace and it would require a fair bit of refactoring to change all my log output to use a separate non-global space so that I don't get this message in my otherwise nicely formatted logs anymore.

Or maybe make it an option to disable?

Orr.... maybe I'm completely misunderstanding and there's a way to disable this message without changing all my references to $log in the system?

We have 40,000+ devices that only output info/error messages rarely and we plan to sync these logs with a logging server, it would be nice if they all didn't report this info line whenever they boot.

**Comment by bbottema** [comment]
Merged. Will do a release soon.

**Comment by drewzh** [comment]
I very much appreciate the work you've done on this amazing module, thanks for understanding :-) :+1:

**Comment by bbottema** [comment]
It's in v1.3.1. Good luck.

Beware, starting at 1.3.0 the package.json main property is now point to the source instead of the dist file. Might not be an issue if you already pointed directly to the dist script or if you are using a tool that understands commonjs require statements.

**Comment by drewzh** [comment]
That's actually fine, I do my own compression etc after the main gets pulled in (automatically with bower/wiredep) so all good. Thanks for the advice :+1:

**Pull request merged**
